# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 4
  sort_reverse: true
  indexpage: page1
  permalink: page:num
  extension: json