# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 4
  sort_reverse: true
  indexpage: page1
  permalink: page:num
  extension: json

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }